export const data = [
  {
    id: 1,
    name: "Albert Flores",
    timestamp: "23 August, 12:00 PM",
    score: "95",
    status: "Shortlisted",
    resume: "Resume.pdf",
    statusColor: "text-green-500",
  },
  {
    id: 2,
    name: "Wade Warren",
    timestamp: "23 August, 12:00 PM",
    score: "88",
    status: "Shortlisted",
    resume: "Resume.pdf",
    statusColor: "text-green-500",
  },
  {
    id: 3,
    name: "Courtney Henry",
    timestamp: "23 August, 12:00 PM",
    score: "75",
    status: "Waitlisted",
    resume: "Resume.pdf",
    statusColor: "text-yellow-500",
  },
  {
    id: 4,
    name: "Jacob Jones",
    timestamp: "23 August, 12:00 PM",
    score: "60",
    status: "Waitlisted",
    resume: "Resume.pdf",
    statusColor: "text-red-500",
  },
  {
    id: 5,
    name: "Jacob Jones",
    timestamp: "23 August, 12:00 PM",
    score: "60",
    status: "Waitlisted",
    resume: "Resume.pdf",
    statusColor: "text-red-500",
  },
  {
    id: 6,
    name: "Jacob Jones",
    timestamp: "23 August, 12:00 PM",
    score: "60",
    status: "Waitlisted",
    resume: "Resume.pdf",
    statusColor: "text-red-500",
  },
  {
    id: 7,
    name: "Jacob Jones",
    timestamp: "23 August, 12:00 PM",
    score: "60",
    status: "Waitlisted",
    resume: "Resume.pdf",
    statusColor: "text-red-500",
  },
  {
    id: 8,
    name: "Jacob Jones",
    timestamp: "23 August, 12:00 PM",
    score: "60",
    status: "Waitlisted",
    resume: "Resume.pdf",
    statusColor: "text-red-500",
  },
  {
    id: 9,
    name: "Jacob Jones",
    timestamp: "23 August, 12:00 PM",
    score: "60",
    status: "Waitlisted",
    resume: "Resume.pdf",
    statusColor: "text-red-500",
  },
  {
    id: 10,
    name: "Jacob Jones",
    timestamp: "23 August, 12:00 PM",
    score: "60",
    status: "Waitlisted",
    resume: "Resume.pdf",
    statusColor: "text-red-500",
  },
  // Add more objects with unique ids
];
