export const data = [
  {
    name: "Albert Flores",
    timestamp: "23 August, 12:00 PM",
    score: "95%",
    status: "Shortlisted",
    resume: "Resume.pdf",
    statusColor: "text-green-500",
  },
  {
    name: "Wade Warren",
    timestamp: "23 August, 12:00 PM",
    score: "88%",
    status: "Shortlisted",
    resume: "Resume.pdf",
    statusColor: "text-green-500",
  },
  {
    name: "Courtney Henry",
    timestamp: "23 August, 12:00 PM",
    score: "75%",
    status: "Waitlisted",
    resume: "Resume.pdf",
    statusColor: "text-yellow-500",
  },
  {
    name: "Jacob Jones",
    timestamp: "23 August, 12:00 PM",
    score: "60%",
    status: "Rejected",
    resume: "Resume.pdf",
    statusColor: "text-red-500",
  },
  {
    name: "Jacob Jones",
    timestamp: "23 August, 12:00 PM",
    score: "60%",
    status: "Rejected",
    resume: "Resume.pdf",
    statusColor: "text-red-500",
  },
  {
    name: "Jacob Jones",
    timestamp: "23 August, 12:00 PM",
    score: "60%",
    status: "Rejected",
    resume: "Resume.pdf",
    statusColor: "text-red-500",
  },
  {
    name: "Jacob Jones",
    timestamp: "23 August, 12:00 PM",
    score: "60%",
    status: "Rejected",
    resume: "Resume.pdf",
    statusColor: "text-red-500",
  },
  {
    name: "Jacob Jones",
    timestamp: "23 August, 12:00 PM",
    score: "60%",
    status: "Rejected",
    resume: "Resume.pdf",
    statusColor: "text-red-500",
  },
  {
    name: "Jacob Jones",
    timestamp: "23 August, 12:00 PM",
    score: "60%",
    status: "Rejected",
    resume: "Resume.pdf",
    statusColor: "text-red-500",
  },
  {
    name: "Jacob Jones",
    timestamp: "23 August, 12:00 PM",
    score: "60%",
    status: "Rejected",
    resume: "Resume.pdf",
    statusColor: "text-red-500",
  },
  {
    name: "Jacob Jones",
    timestamp: "23 August, 12:00 PM",
    score: "60%",
    status: "Rejected",
    resume: "Resume.pdf",
    statusColor: "text-red-500",
  },

  {
    name: "Jacob Jones",
    timestamp: "23 August, 12:00 PM",
    score: "60%",
    status: "Rejected",
    resume: "Resume.pdf",
    statusColor: "text-red-500",
  },
  {
    name: "Jacob Jones",
    timestamp: "23 August, 12:00 PM",
    score: "60%",
    status: "Rejected",
    resume: "Resume.pdf",
    statusColor: "text-red-500",
  },
  {
    name: "Jacob Jones",
    timestamp: "23 August, 12:00 PM",
    score: "60%",
    status: "Rejected",
    resume: "Resume.pdf",
    statusColor: "text-red-500",
  },
  {
    name: "Jacob Jones",
    timestamp: "23 August, 12:00 PM",
    score: "60%",
    status: "Rejected",
    resume: "Resume.pdf",
    statusColor: "text-red-500",
  },
  {
    name: "Jacob Jones",
    timestamp: "23 August, 12:00 PM",
    score: "60%",
    status: "Rejected",
    resume: "Resume.pdf",
    statusColor: "text-red-500",
  },
  {
    name: "Jacob Jones",
    timestamp: "23 August, 12:00 PM",
    score: "60%",
    status: "Rejected",
    resume: "Resume.pdf",
    statusColor: "text-red-500",
  },
  {
    name: "Jacob Jones",
    timestamp: "23 August, 12:00 PM",
    score: "60%",
    status: "Rejected",
    resume: "Resume.pdf",
    statusColor: "text-red-500",
  },
  {
    name: "Jacob Jones",
    timestamp: "23 August, 12:00 PM",
    score: "60%",
    status: "Rejected",
    resume: "Resume.pdf",
    statusColor: "text-red-500",
  },
  {
    name: "Jacob Jones",
    timestamp: "23 August, 12:00 PM",
    score: "60%",
    status: "Rejected",
    resume: "Resume.pdf",
    statusColor: "text-red-500",
  },
  {
    name: "Jacob Jones",
    timestamp: "23 August, 12:00 PM",
    score: "60%",
    status: "Rejected",
    resume: "Resume.pdf",
    statusColor: "text-red-500",
  },
  {
    name: "Jacob Jones",
    timestamp: "23 August, 12:00 PM",
    score: "60%",
    status: "Rejected",
    resume: "Resume.pdf",
    statusColor: "text-red-500",
  },
  {
    name: "Jacob Jones",
    timestamp: "23 August, 12:00 PM",
    score: "60%",
    status: "Rejected",
    resume: "Resume.pdf",
    statusColor: "text-red-500",
  },
  {
    name: "Jacob Jones",
    timestamp: "23 August, 12:00 PM",
    score: "60%",
    status: "Rejected",
    resume: "Resume.pdf",
    statusColor: "text-red-500",
  },

];